FROM docker:17.06

RUN apk add --no-cache \
      git curl tar make bash grep jq \
      openssh-client ca-certificates

RUN apk add --no-cache py-pip \
      && pip install --no-cache-dir docker-compose awscli awslogs
